### ISSUE TITLE
Not Login with Google

### ISSUE THREAD

**Issue by pharidali** [NovaViper/TrinityLocker#3]
Their is Google Login Problem..

**Comment by NovaViper** [comment]
Hey, try now with the latest commit. Also, may I ask how did you get the app running on your device? I THINK I would have to export a signed apk in order for it to work.

**Comment by pharidali** [comment]
Please upload demo

**Comment by NovaViper** [comment]
Hey, I'm actually getting ready to upload the app on Google Play for Alpha testing, so you should be able to play around with the app on there; I'm just putting in some more stuff (and fixing a few errors I found). And on my side, I managed to fix that error too

**Comment by NovaViper** [comment]
Also, since I'm going in that direction, I need to ensure that the app follows Google's basic policies

**Comment by NovaViper** [comment]
@pharidali Sorry for the massive delay! I've been really busy with finishing up school, I have one more year in high school before college so time is pretty crunched. But fear not, I have _not_ forgotten about the app! I'm actually planning on completely taking the app apart and rewriting it from the ground up (since I've forgotten what most of the code, thus I must reteach myself it). I'm going to first start off with the very basic structure and send that out for you to test (without the google sign in and such)

**Comment by pharidali** [comment]
Thank You Soo Much. 😊😊

**Comment by NovaViper** [comment]
Sorry for not responding in so long, I've been busy with school. I actually just started rewriting the app completely from the ground up. So I have completely removed the option to sign into your Google account (as for now) until I can get the backbone of the app functioning.
